apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s:%s" "system:openshift:scc:privileged" .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s" "system:openshift:scc:privileged" }}
subjects:
- kind: ServiceAccount
  name: {{ include "this.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}