apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "this.serviceAccountName" . }}
  namespace: {{ template "this.namespace" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}