replicaCount: 1

annotations: {}

podAnnotations: {}

image:
  pullSecrets: []
  repository: "mcr.microsoft.com/azure-cli"
  pullPolicy: Always
  
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
  
securityContext:
  runAsUser: 0
  runAsGroup: 0
  
resources: {}

serviceAccount:
  annotations: {}